/* Auto-generated by build_tickers_stdlib.py — do not edit by hand. */
window.FT_TICKERS = {
  "lastUpdated": "Jun 24, 2026",
  "isSample": false,
  "data": {
    "SCHD": {
      "name": "Schwab US Dividend Equity ETF",
      "price": 31.71,
      "yield": 3.33,
      "freq": "Quarterly"
    },
    "VYM": {
      "name": "Vanguard High Dividend Yield ETF",
      "price": 158.37,
      "yield": 2.29,
      "freq": "Quarterly"
    },
    "DGRO": {
      "name": "iShares Core Dividend Growth ETF",
      "price": 75.4,
      "yield": 1.96,
      "freq": "Quarterly"
    },
    "VIG": {
      "name": "Vanguard Dividend Appreciation ETF",
      "price": 235.45,
      "yield": 1.47,
      "freq": "Quarterly"
    },
    "HDV": {
      "name": "iShares Core High Dividend ETF",
      "price": 27.33,
      "yield": 2.91,
      "freq": "Quarterly"
    },
    "DIVO": {
      "name": "Amplify CWP Enhanced Dividend Income ETF",
      "price": 45.98,
      "yield": 6.43,
      "freq": "Monthly"
    },
    "O": {
      "name": "Realty Income Corp",
      "price": 61.5,
      "yield": 5.27,
      "freq": "Monthly"
    },
    "MAIN": {
      "name": "Main Street Capital Corp",
      "price": 49.6,
      "yield": 8.65,
      "freq": "Monthly"
    },
    "ARCC": {
      "name": "Ares Capital Corp",
      "price": 17.89,
      "yield": 10.73,
      "freq": "Quarterly"
    },
    "JEPI": {
      "name": "JPMorgan Equity Premium Income ETF",
      "price": 56.33,
      "yield": 8.14,
      "freq": "Monthly"
    },
    "JEPQ": {
      "name": "JPMorgan Nasdaq Equity Premium Income ETF",
      "price": 60.24,
      "yield": 10.16,
      "freq": "Monthly"
    },
    "QYLD": {
      "name": "Global X Nasdaq 100 Covered Call ETF",
      "price": 18.06,
      "yield": 11.62,
      "freq": "Monthly"
    },
    "RYLD": {
      "name": "Global X Russell 2000 Covered Call ETF",
      "price": 15.86,
      "yield": 11.68,
      "freq": "Monthly"
    },
    "XYLD": {
      "name": "Global X S&P 500 Covered Call ETF",
      "price": 40.43,
      "yield": 10.48,
      "freq": "Monthly"
    },
    "SPYI": {
      "name": "NEOS S&P 500 High Income ETF",
      "price": 52.58,
      "yield": 12.93,
      "freq": "Monthly"
    },
    "QQQI": {
      "name": "NEOS Nasdaq 100 High Income ETF",
      "price": 55.51,
      "yield": 14.87,
      "freq": "Monthly"
    },
    "SDIV": {
      "name": "Global X SuperDividend ETF",
      "price": 24.2,
      "yield": 9.37,
      "freq": "Monthly"
    },
    "PFF": {
      "name": "iShares Preferred & Income Securities ETF",
      "price": 30.78,
      "yield": 5.55,
      "freq": "Monthly"
    },
    "KO": {
      "name": "Coca-Cola Co",
      "price": 81.26,
      "yield": 2.56,
      "freq": "Quarterly"
    },
    "PEP": {
      "name": "PepsiCo Inc",
      "price": 142.9,
      "yield": 4.02,
      "freq": "Quarterly"
    },
    "JNJ": {
      "name": "Johnson & Johnson",
      "price": 240.27,
      "yield": 2.18,
      "freq": "Quarterly"
    },
    "T": {
      "name": "AT&T Inc",
      "price": 22.5,
      "yield": 4.94,
      "freq": "Quarterly"
    },
    "VZ": {
      "name": "Verizon Communications",
      "price": 45.75,
      "yield": 6.05,
      "freq": "Quarterly"
    },
    "MO": {
      "name": "Altria Group Inc",
      "price": 71.43,
      "yield": 5.94,
      "freq": "Quarterly"
    },
    "ABBV": {
      "name": "AbbVie Inc",
      "price": 233.44,
      "yield": 2.89,
      "freq": "Quarterly"
    }
  }
};
